version: "3.8"
services:
  meetup_presto:
    build: .
    ports:
      - "8080:8080"
  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
