apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-coordinator
  labels:
    app: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      containers:
      - name: coordinator
        image: warsaw-data-meetup/coordinator:350
        ports:
        - containerPort: 8080
